name: Publish CLI on Release

on:
  release:
    types: [created]

jobs:
  typecheck:
    uses: ./.github/workflows/build-and-typecheck.yml

  publish:
    runs-on: ubuntu-latest
    needs: typecheck
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build CLI
        run: |
          cd apps/cli
          bun run build
          
      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
        
      - name: Publish to npm
        run: |
          cd apps/cli
          npm publish --access public
